name: Build and Push Docker Images

on:
  push:
    branches: ["main"]

jobs:
  build-push:
    runs-on: ubuntu-latest

    env:
      BACKEND_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/springboot-app
      FRONTEND_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/angular-app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Spring Boot
        uses: docker/build-push-action@v6
        with:
          context: ./springboot/app
          file: ./springboot/app/Dockerfile
          push: true
          tags: |
            ${{ env.BACKEND_IMAGE }}:latest
            ${{ env.BACKEND_IMAGE }}:${{ github.sha }}

      - name: Build & Push Angular
        uses: docker/build-push-action@v6
        with:
          context: ./angular-app
          file: ./angular-app/Dockerfile
          push: true
          tags: |
            ${{ env.FRONTEND_IMAGE }}:latest
            ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
